### ISSUE TITLE
今後の予定

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#1]
mikutter_slackの短期〜中期的目標を備忘録的に書いていきます. (順不同) 
- [x] ~~[omniauth-slack](https://github.com/kmrshntr/omniauth-slack)を用いたOAuth認証にする (なんか他にいいのあれば教えてください)~~  
WebRickとHTTPClientで実装しました
- [x] mikutterにSlack専用のタブを作る
- [x] 任意の一つのチャンネルを上記タブに表示する機能を作る
- [x] Emoji対応 ([APIレファレンス](https://api.slack.com/methods/emoji.list))
- [x] 認証用やチャンネルの指定のためにmikutterの設定画面に設定項目を作成する

まずはこんな感じを予定してます.  
以上.

**Comment by toshia** [comment]
>  mikutterにSlack専用のタブを作る
>  任意の一つのチャンネルを上記タブに表示する機能を作る

この二点に関しては、タブを作成するんじゃなくて抽出タブデータソースを提供すると考えてほしい。抽出タブに関してよくわからんかったらこっちで参考URL探すのできいてくれ（すまんな）
データソースにすれば、チャンネルのミキシングやフィルタリングが自由にできるようになるし、Twitterのホームタイムラインとかもプラグイン廃止して抽出タブ化しようという計画が密かに進行してる

>  Emoji

現状ではできないので、Entityが画像をオーバレイできるようにする必要がある気がするな？まずmikutter側の対応がいるので、そういう感じのチケットを投げてくれ。意味不明だったら俺がチケット作ってもいいよ

>  認証

:ito-life:

**Comment by Na0ki** [comment]
> Entityが画像をオーバレイできるようにする必要がある気がする

がわかりません！
:apa: みたいな文字列を絵文字に変換した際に、絵文字をtext内に表示する機構がないから、画像をtext内に表示できるようにする必要があるということでしょうか

**Comment by toshia** [comment]
> > Entityが画像をオーバレイできるようにする必要がある気がする
> 
> がわかりません！

悪い、手段としてEntityの拡張で行こうかなという考えがあったのでいろいろ余分なことを書いてしまったが、要は現状のmikutterではできないし、そういうことが可能になるアップデートの予定もないよ、ということ。

**Comment by Na0ki** [comment]
了解です
ありがとうございます

**Comment by Na0ki** [comment]
redmineにチケット投げたら閉じる

**Comment by Na0ki** [comment]
投げたので閉じる
