### ISSUE TITLE
記述が汚い

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#18]
[ここ](https://github.com/Na0ki/mikutter_slack/blob/master/mikutter_slack.rb#L68) や [ここ](https://github.com/Na0ki/mikutter_slack/blob/master/mikutter_slack.rb#L84) の `Time.at(Float(data['ts']).to_i)` がもう少し綺麗にできないか  

`data['ts']` は unixtime を浮動小数点付きで返すため、整数に丸めて Time 型にしている

**Comment by toshia** [comment]
`data['ts']`の内容に因るけど、Stringを期待するのであれば、単に `Time.at(data['ts'].to_i)` と書けると思う。
ただ、Float()はnilとか変な値を渡すと例外を投げてくれるが、to_iは0を返すという違いがある。変な値のまま処理が進んでしまうので良くないかも。

```
pry(main)> nil.to_i
=> 0
```

そういう意味では、厳密に同じ挙動でそれよりスマートな書き方はぱっと思いつかないなあ

**Comment by Na0ki** [comment]
なるほど
変な値であれば例外投げて欲しいので、今のままでとりあえずはよさそうですね
ありがとうございます

**Comment by toshia** [comment]
closeされましたが、例外はキャッチしないとmikutterがクラッシュするということと、Twitter APIだったらそういう場所に`nil`を詰めて渡されて本当にクラッシュしてしまうことがしばしばあるということを伝えておきます。
参考: https://github.com/cosmo0920/mikutter_filter/pull/7

**Comment by Na0ki** [comment]
@Na0ki TODO: [ここ](https://github.com/Na0ki/ruby-slack-sample) でテストする

**Comment by Na0ki** [comment]
`data['ts']` をnilチェックなどしておかしくない場合は `Time.at(data['ts'].to_i)` で通してしまえばいいですかね
取れない場合はどうしようってなりますが

**Comment by Na0ki** [comment]
trapしているので対応完了とする
