### ISSUE TITLE
Plugin#defined_time を使う

### ISSUE THREAD

**Issue by toshia** [Na0ki/mikutter_slack#19]
現在、プラグインのロード時のタイムスタンプを取っているが

``` ruby
@defined_time = Time.new.freeze
```

実は `Plugin#defined_time` というメソッドが、そのプラグインをロードした時刻(Time)を返すようになっているので、それを使うと、上のような行は消せる

**Comment by Na0ki** [comment]
確かにplugin.rbのinitializeに上記と全く同じものがありました
pryでPlugin.createしてみたら、オブジェクトの中に@defined_timeを確認できました

**Comment by Na0ki** [comment]
コミット[60a4038](https://github.com/Na0ki/mikutter_slack/commit/60a4038fe1bcea4ec1dac035ea2712b57c04d219) で対応
