### ISSUE TITLE
Realtime APIの受信を別のところで行う

### ISSUE THREAD

**Issue by toshia** [Na0ki/mikutter_slack#20]
mikutter_slack.rbで、 `RTM` , `EVENTS` という定数をトップレベル定義していて衝突の危険性がある。Plugin::Slackに定義して衝突を回避したほうが良い。

でもRTMを使っている部分を見ると、Pluginのインスタンスを特に利用している様子がなく、無理にPluginブロックの中に書く必要はない。将来的に複数のSlackチームをサポートしたいということだし、それも視野に入れてそういうクラスを作ったほうが良さそう。 slack_api.rb とかにそういう機能を持たせるのが自然なんだろうか

**Comment by Na0ki** [comment]
`RTM.on :hoge do end` みたいなやつは slack_api.rb にまとめてもいい気はします。
ただその場合、既存のslack_api.rbに定義されてるメソッドが同居してしますと煩雑になるので util.rb（適当）みたいなものに移動すべきでしょうか
