### ISSUE TITLE
Plugin slugを slack に変更してはどうか

### ISSUE THREAD

**Issue by toshia** [Na0ki/mikutter_slack#22]
今はmikutter_slackというPlugin slugだが、単に「slack」としたら良いと思う。

リポジトリ名は「mikutter_」prefixをつけているとmikutterプラグインだということが分かって意味があるが(これを禁止すると、例えばsystemdと連携する変なプラグインを書いた場合、**systemd**という超凶悪な名前のリポジトリができる)、Plugin slugはmikutterの中でプラグイン同士を識別するものなので、もうmikutterプラグインであることはわかっている。だから「mikutter_」というprefixを付ける意味は薄い。

ちなみに俺が過去に送ったpull-reqで、`Plugin::Slack` というmoduleを作ったが、これは申し訳ないことに間違っていて、slugをCamelCaseにしたものにしなきゃいけないので `Plugin::MikutterSlack` にしなければいけない。slugを「slack」にすれば、moduleの名前は変更しなくてよい。

当然これをやると、現在このプラグインを使っている人はディレクトリ名をリネームする必要があるが、だからこそ変更するなら今のうちだと思う。
そうする場合、今後利用しようとするユーザのために、適切なディレクトリ名でcloneするためのコマンドをREADMEに書いておくと親切。

**Comment by Na0ki** [comment]
そうですね
mikutter内でプレフィックスは冗長なのでslugを「slack」に変更します

**Comment by Na0ki** [comment]
「slack」に変更した場合に、ライブラリとして使ってるslackとのバッティングとかってないんでしょうか
スラグはmikutter側の管理ということで問題ないのかな

**Comment by Na0ki** [comment]
コミット[4eb2ff1](https://github.com/Na0ki/mikutter_slack/commit/4eb2ff14b9128fd464ad52568c3c8634bfa5b056)で対応済み
バッティングしないことも確認済み
