### ISSUE TITLE
slackの画像展開

### ISSUE THREAD

**Issue by toshia** [Na0ki/mikutter_slack#32]
slackの添付画像は、画像のURLっぽいくせに実際にはHTMLになってるので、mikutterのイメージビューアで開くとエラーになる。
twitpicとかd250g2.comとかと同じように、一種の画像サービスとしてslackの画像URLを登録してやれば、イメージビューアで開くことができるようになる

**Comment by rinsuki** [comment]
https://github.com/mikutter/mikutter/blob/666f03d6ed67736d3f76d1c16d37d03b78cb46b5/core/plugin/photo_support/photo_support.rb d250g2とかの実装はここっぽい

**Comment by Na0ki** [comment]
その部分は把握してるんだけど、mikutterのソースのopenimg内に画像直リンクということで、jpgやpngにマッチする部分があって、プラグイン側でdefimageopenerを定義してもその前にmikutterのopenimgが適用されてしまう。
photo_supportに書いてしまうと、サービスが増えるごとにmikutter側が対応しなくてはならなくなるので、よろしく無いです。
この辺はチケット作ってmikutter側にプラグインのopenerが適用されるような機能をつける要望を出すのがいいかもしれないです。
チケットに関しては出します。

**Comment by Na0ki** [comment]
slack_gui の [2b7b2fd](https://github.com/Na0ki/mikutter_slack_gui/commit/2b7b2fde4aa1b1114d316d6da64b5113b8fc1469) で対応完了です。  
GUIに関する実装なので、本プラグインには実装しません。
