### ISSUE TITLE
achievementの扱いを考える

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#42]
実績解除のために、 achievementプラグインを利用している。
しかしachievementプラグインがguiに依存しているため、今後も利用していくかを考える必要がある。
現在guiに依存しているコードはコレのみで、それがなければslackプラグイン単体での実行も可能になる。

**Comment by toshia** [comment]
ちょっと考えたけどachievementがgtkに依存していたらおかしいけど、guiに依存しているのは自然な気がするので、slackのUIを扱うためのプラグインがachievementを使った機能を提供するようにしたらいいと思う

**Comment by Na0ki** [comment]
achievement及びactivityは [slack_gui](https://github.com/Na0ki/mikutter_slack_gui) に移動しました。
コマンドなどもguiに移動したので、コマンド使う方は本プラグインとslack_guiの二つをインストールするようにしてください。
