### ISSUE TITLE
Privateなチャンネルの発言が取得出来てない

### ISSUE THREAD

**Issue by whywaita** [Na0ki/mikutter_slack#49]
- 自分のアカウントでOAuth認証済み
- 自分が参加しているプライベートなチャンネルの発言が取得出来てない
- 公式のクライアントからだと見られるチャンネル
- そもそもデータソースとして(プライベートチャンネルが)出てきてない？

**Comment by Na0ki** [comment]
そもそもデータソースに提供してないです
じつはソースコードの中にとって来るのは形だけ用意してありますが、使ってない状態です。
そのうち移行する。（いつとは行っていない）
