### ISSUE TITLE
ユーザー名が error(ユーザーID) になる

### ISSUE THREAD

**Issue by whywaita** [Na0ki/mikutter_slack#50]
![2017-01-23 11 25 01](https://cloud.githubusercontent.com/assets/4568341/22189222/a4a2c098-e15e-11e6-9c6b-adbdc8ae0841.png)

上記の画像のように、ユーザが何らかの行動をした際のログが `error(ユーザーIDっぽいもの)` のように表示されてしまう

- join/left
- ファイルアップロード

で確認

**Comment by Na0ki** [comment]
7bb4d4db78a63352de01b029ffa8873f27800c90 で修正完了
