### ISSUE TITLE
< > & のエスケープ表示

### ISSUE THREAD

**Issue by tsutsui** [Na0ki/mikutter_slack#58]
この投稿
https://d250g2.slack.com/archives/general/p1486735253004664
ですが、 mikutter 上だと > が & gt ; で出てきます。

![slack-escape](https://cloud.githubusercontent.com/assets/3054480/22831046/35a7d5c4-efec-11e6-8bdf-b63db97277a5.png)

mikutter 本体でもこのへん Twitter 側の返す値に翻弄されていた歴史がありますが、Slack側の挙動と合わせて仕様を定義する必要があるような。

**Comment by rinsuki** [comment]
mikutterの実装はここですね https://github.com/mikutter/mikutter/blob/9244031d9814bb176802e64d229b8bc642be6edd/core/lib/retriever/mixin/message_mixin.rb#L132

**Comment by Na0ki** [comment]
channel topicに文字列として `<` もしくは `>` など + URLなど内部で `<何か>` に変換される文字列が存在する場合に `>` が `gt ;` になるみたいです。
修正したので確認お願いします。

**Comment by tsutsui** [comment]
https://github.com/Na0ki/mikutter_slack/commit/9863d3612d7591e7e15d30d8d075945046e8370c で試しましたがまだダメという気が
![issue 58](https://cloud.githubusercontent.com/assets/3054480/22979289/2f8ecdb4-f3d9-11e6-87e7-feab145e7266.png)
webだとこうです
![issue 58-web](https://cloud.githubusercontent.com/assets/3054480/22979357/6a739a54-f3d9-11e6-9e0b-f576c58c3f5e.png)

**Comment by Na0ki** [comment]
@tsutsui としぁ大先生が修正してくれました
確認をお願いします

**Comment by tsutsui** [comment]
https://github.com/toshia/mikutter_slack/commit/557d20328ce1da7cb0779aa7ebfe249851dde06b で試しました。直っているようです。ありがとうございます。
![issue 58-fixed](https://cloud.githubusercontent.com/assets/3054480/23021596/11aa3d12-f490-11e6-8d87-3468c82158cc.png)

抹茶チョコの返礼は何にしようかと考える今日このごろ。
