### ISSUE TITLE
認証時に田代砲を打っている

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#61]
ログを添付するが、認証時にユーザー一覧取得を何回もリクエストしている。
そのため、起動時に毎回 `please relax` とSlackになだめられるといった問題が発生してしまっている。
`/Users/ahiru/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/slack-api-1.3.0/lib/slack/request.rb` の10行目に以下のコードを書いて確認して見た。
```
p "request, #{path}, #{options}"
```
[tashiro.txt](https://github.com/Na0ki/mikutter_slack/files/784913/tashiro.txt)

**Comment by toshia** [comment]
https://github.com/Na0ki/mikutter_slack/blob/master/entity/message_entity.rb#L70

userのキャッシュがない場合、田代砲打ってそうですね

**Comment by Na0ki** [comment]
アパの権限を奪ったので平和が訪れた
